# Generated by Django 3.2 on 2021-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mditem',
            name='tags',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
